export const CurrencyList = [
  {name: 'Afghani', value: 'AFN'},
  {name: 'European euro', value: 'EUR'},
  {name: 'United States dollar', value: 'USD'},
  {name: 'East Caribbean dollar', value: 'XCD'},
  {name: 'Argentine peso', value: 'ARS'},
  {name: 'Armenian dram', value: 'AMD'},
  {name: 'Australian dollar', value: 'AUD'},
  {name: 'Bahamian dollar', value: 'BSD'},
  {name: 'Bahraini dinar', value: 'BHD'},
  {name: 'Brazilian real', value: 'BRL'},
  {name: 'Bulgarian lev', value: 'BGN'},
  {name: 'West African CFA franc', value: 'XOF'},
  {name: 'Canadian dollar', value: 'CAD'},
  {name: 'Central African CFA franc', value: 'XAF'},
  {name: 'New Zealand dollar', value: 'NZD'},
  {name: 'Chinese Yuan Renminbi', value: 'CNY'},
  {name: 'Egyptian pound', value: 'EGP'},
  {name: 'Falkland Islands pound', value: 'FKP'},
  {name: 'East Caribbean dollar', value: 'XCD'},
  {name: 'Hong Kong dollar', value: 'HKD'},
  {name: 'Indian rupee', value: 'INR'},
  {name: 'Iranian rial', value: 'IRR'},
  {name: 'Iraqi dinar', value: 'IQD'},
  {name: 'Israeli new shekel', value: 'ILS'},
  {name: 'Japanese yen', value: 'JPY'},
  {name: 'Kazakhstani tenge', value: 'KZT'},
  {name: 'Liberian dollar', value: 'LRD'},
  {name: 'Malawian kwacha', value: 'MWK'},
  {name: 'Mexican peso', value: 'MXN'},
  {name: 'Nepalese rupee', value: 'NPR'},
  {name: 'Nicaraguan cordoba', value: 'NIO'},
  {name: 'Omani rial', value: 'OMR'},
  {name: 'Pakistani rupee', value: 'PKR'},
  {name: 'Philippine peso', value: 'PHP'},
  {name: 'Qatari riyal', value: 'QAR'},
  {name: 'Romanian leu', value: 'RON'},
  {name: 'Russian ruble', value: 'RUB'},
  {name: 'Rwandan franc', value: 'RWF'},
  {name: 'Saint Helena pound', value: 'SHP'},
  {name: 'Saudi Arabian riyal', value: 'SAR'},
  {name: 'Singapore dollar', value: 'SGD'},
  {name: 'South African rand', value: 'ZAR'},
  {name: 'South Korean won', value: 'KRW'},
  {name: 'Sudanese pound', value: 'SDG'},
  {name: 'Swedish krona', value: 'SEK'},
  {name: 'Turkish lira', value: 'TRY'},
  {name: 'Turkmen manat', value: 'TMT'},
  {name: 'Ukrainian hryvnia', value: 'UAH'},
  {name: 'Pound sterling', value: 'GBP'},
  {name: 'Venezuelan bolivar', value: 'VEF'},
  {name: 'Vietnamese dong', value: 'VND'},
  {name: 'Yemeni rial', value: 'YER'},
];
